src/bas.website.prj/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using bas.website.Service;
using System.Data;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using bas.website.Models.Data;

namespace bas.website.Controllers
{
    public class CalculatorController : Controller
    {
        /// <summary>
        /// Подключение к базе данных
        /// </summary>
        public BankDbContext db = new (ProjectConfig.Connection);

        /// <summary>
        /// Критерии оценки истории кредитов
        /// </summary>
        readonly Dictionary<decimal, string[]> PercentCrit = new () 
        {
            { 0, new string[2] { "0", "excellently" } },
            { (decimal)-0.3, new string[2] { "0.3", "good" } },
            { (decimal)-0.5, new string[2] { "0.5", "good" } },
            { (decimal)-0.7, new string[2] { "0.7", "good" } },
            { (decimal)-0.9, new string[2] { "0.9", "good" } },
            { (decimal)-1.1, new string[2] { "1.0", "normally" } },
            { (decimal)-1.3, new string[2] { "1.3", "normally" } },
            { (decimal)-1.5, new string[2] { "1.5", "normally" } },
            { (decimal)-1.7, new string[2] { "1.7", "normally" } },
            { (decimal)-1.9, new string[2] { "1.9", "normally" } },

        };


        /// <summary>
        /// Калькулятор
        /// </summary>
        /// <returns>Рендер страницы</returns>

        [Route("/credit/calculator")]
        public IActionResult CreditCalc()
        {
            /// Проверка авторизации пользователя
            if (User.Identity.IsAuthenticated) ViewBag.Authentication = true;
            else ViewBag.Authentication = false;

            return View();
        }


        /// <summary>
        /// Авторизация
        /// </summary>
        /// <param name="model">Модель Формы авторизации</param>
        /// <returns>Редирект на страницу калькулятора</returns>
        [HttpPost]
        [Route("/credit/calculator")]
        public async Task<IActionResult> CreditCalcAsync(LoginViewModel model)
        {
            /// Поиск пользователя
            var user = await db.Bank_client
                .SingleOrDefaultAsync(x => x.Client_login == model.UserLogin && x.Client_password == model.Password);


            /// Если пользователя нет в базе данных
            if (user == null)
            {
                ModelState.TryAddModelError("", "Пользователь не найден!");
                ViewBag.Authentication = false;
                return View();
            }


            /// Выборка всей истории клиента
            var history = db.Bank_client_history
                .Include(ch => ch.Bank_status_history)
                .Include(ch => ch.Bank_client)
                .Where(ch => ch.Clihis_client == user.Client_id);

            /// Запись результата истории кредита при чистой истории кредитов
            var CreditResult = new string[2] { "0", "excellently" };


            /// Если список истории кредитов не пуст
            if (history.Any()) CreditResult = GetIndiPercent(history);


            /// Запись данных в Cookie
            HttpContext.Response.Cookies.Append("UserName", user.Client_name);
            HttpContext.Response.Cookies.Append("UserSurname", user.Client_surname);
            HttpContext.Response.Cookies.Append("UserSex", user.Client_sex.ToString());
            HttpContext.Response.Cookies.Append("UserID", user.Client_id.ToString());
            HttpContext.Response.Cookies.Append("UserPercent", CreditResult[0]);
            HttpContext.Response.Cookies.Append("UserCredStatus", CreditResult[1]);


            /// Авторизация с помощью Клеймов
            var claims = new List<Claim> { new Claim("Name", user.Client_login) };
            var claimIdentity = new ClaimsIdentity(claims, "Cookie");
            var claimPrincipal = new ClaimsPrincipal(claimIdentity);
            await HttpContext.SignInAsync("Cookie", claimPrincipal);

            return Redirect("/credit/calculator");
        }


        /// <summary>
        /// Выйти из аккаунта
        /// </summary>
        /// <returns>Перенаправление</returns>
        public IActionResult CreditCalcLogOff()
        {
            /// Удаление Cookies из сайта
            HttpContext.Response.Cookies.Delete("UserName");
            HttpContext.Response.Cookies.Delete("UserSurname");
            HttpContext.Response.Cookies.Delete("UserPercent");
            HttpContext.Response.Cookies.Delete("UserCredStatus");
            HttpContext.Response.Cookies.Delete("UserID");
            HttpContext.SignOutAsync("Cookie");


            return Redirect("/credit/calculator");
        }


        /// <summary>
        /// Функция дающая расчет оценки кредитной истории
        /// </summary>
        /// <param name="client_id"> Индификатор пользователя </param>
        /// <param name="hist"> История клиента </param>
        /// <returns>Массив с оценкой</returns>
        private string[] GetIndiPercent(IQueryable<Bank_client_history> history)
        {
            /// Выходной массив
            string[] percent = new string[2];

            /// Сумма
            decimal sum = 0;

            /// Сумма статуса
            foreach (var r in history) sum += r.Bank_status_history.Status_value;


            /// Среднее значение
            decimal rang = sum / history.Count();


            /// Сравноение со словарем Критериев для выставления рейтинка истории
            foreach (var row in PercentCrit)
            {
                /// Сравнение Ключем(Баллом) с подсчитанным рейтингом
                if (row.Key <= rang)
                {
                    percent = row.Value;
                    break;
                }
                else
                {
                    percent[0] = "2.3";
                    percent[1] = "satisfactory";
                }
            }


            return percent;
        }

    }


    /// <summary>
    /// Модель Формы авторизации
    /// </summary>
    public class LoginViewModel
    {
        public string UserLogin { get; set; }
        public string Password { get; set; }

    }

}

src/bas.website.prj/Controllers/ProfileController.cs
using bas.website.Models.Data;
using bas.website.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace bas.website.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {

        /// <summary>
        /// Подключение к базе данных
        /// </summary>
        public BankDbContext db = new (ProjectConfig.Connection);

        [Route("/credit/user/history")]
        public IActionResult History()
        {

            var user = int.Parse(HttpContext.Request.Cookies["UserID"]);

            var history = db.Bank_client_history
                .Include(h => h.Bank_client)
                .Include(h => h.Bank_currency)
                .Include(h => h.Bank_status_history)
                .Where(h => h.Clihis_client == user);

            ViewBag.HistNull = false;

            if (!history.Any()) ViewBag.HistNull = true;

            return View(history.ToList());
        }
    }
}

src/bas.website.prj/Views/Calculator/CreditCalc.cshtml
@model LoginViewModel;


@using bas.website.Service

@{ 
    ViewBag.Title = CreditCalcConfig.Title;
    ViewBag.IconPage = CreditCalcConfig.IconPage;
}


<div class="container-fluid content-block">

    <div id="oper-main" class="content-info-main-block container">

        <h1>Модуль - Кредитный калькулятор </h1>

        @{
            if (@ViewBag.Authentication)
            {
                <div id="acc" class="acc-block">
                            <div class="acc-data-user">

                                @{
                                    if (Context.Request.Cookies["UserSex"] == "True")
                                    {
                                        <img src="~/img/status/user.png" alt="">
                                    }
                                    else
                                    {
                                        <img src="~/img/status/userW.png" alt="">
                                    }
                                }

                                <span>Добро пожаловать, @{ @Context.Request.Cookies["UserName"]}  @{@Context.Request.Cookies["UserSurname"]}.</span>
                                <span>
                                    Ваша кредитная история - @{

                                        if (Context.Request.Cookies["UserCredStatus"] == "excellently")
                                        {
                                            <b style="color:#4cff00"> Отлично </b>
                                        }
                                        else if (Context.Request.Cookies["UserCredStatus"] == "good")
                                        {
                                            <b style="color:#b6ff00"> Хорошо </b>
                                        }
                                        else if (Context.Request.Cookies["UserCredStatus"] == "normally")
                                        {
                                            <b style="color:#ffd800"> Нормально </b>
                                        }
                                        else if (Context.Request.Cookies["UserCredStatus"] == "satisfactory")
                                        {
                                            <b style="color:#ff6a00"> Удовлетворительно </b>
                                        }

                                    }
                                </span>
                            </div>
                    <div class="profile-button-block row">
                        <a asp-controller="Profile" asp-action="History" title="История кредитов">История кредитов</a>
                        <a asp-controller="Calculator" asp-action="CreditCalcLogOff" title="Выйти">Выйти</a>
                    </div>
                </div>
            }
            else
            {
                <div id="sign-in" class="sign-in-block row">

                    <div class="sign-in-text-block col-12 col-md-12 col-lg-6">
                        <p>
                            Для "персонального" процента для подсчета пользовательского кредита, необходима авторизация
                        </p>
                    </div>
                    <div class="sign-in-form-block col-12 col-md-12 col-lg-6">
                        <form asp-controller="Calculator" asp-action="CreditCalc" method="post">
                            <div>
                                <H3>Авторизация</H3>

                                <div class="calc-to-block">
                                    <h4>Логин</h4>
                                    <input asp-for="UserLogin" value="" class="calc-input" required>
                                </div>
                                <div class="calc-to-block">
                                    <h4>Пароль</h4>
                                    <input type="password" asp-for="Password" value="" class="calc-input" required>
                                </div>

                                <div asp-validation-summary="All"></div>

                            </div>
                            <button type="submit" class="get-button get-value-block">
                                Войти
                            </button>
                        </form>
                    </div>
                </div>
            }
        }


        <div class="calc-block">
                <div class="calc-to-block">
                    <h4>Сумма займа</h4>
                    <div>
                        <input id="sum" value="1000" type="number" class="calc-input" required>
                    </div>
                </div>
                <div id="cur" class="calc-to-block">
                    <h4>Валюта</h4>
                    <button type="button" data-currency="rub" data-currency-active="true" class="currency-button currency-active">&#8381;</button>
                    <button type="button" data-currency="dol" data-currency-active="false" class="currency-button ">&#36;</button>
                    <button type="button" data-currency="eur" data-currency-active="false" class="currency-button">&#8364;</button>
                </div>
                <div class="calc-to-block">
                    <h4>Информация о целях кредита</h4>
                    <select id='pur' class="calc-select">
                        <option value="5.6" title="От 5.6 %">Образовательные услуги</option>
                        <option value="11.9" title="От 11.9 %">Ремонт</option>
                        <option value="10.6" title="От 10.6 %">Автомобиль</option>
                        <option value="10.1" title="От 10.1 %">Недвижемость</option>
                        <option value="9.2" title="От 9.2 %">Бизнес</option>
                        <option value="10.6" title="От 10.6 %">Отпуск</option>
                        <option value="6.3" title="От 6.3 %">Медицинские услуги</option>
                        <option value="12" title="От 12 %">Бытовая техника и мебель</option>
                        <option value="13.1" title="От 13.1 %">Другое</option>
                    </select>
                </div>
                <div class="calc-to-block calc-percent">
                    <h4>Процентная ставка</h4>
                    <input id="rate" value="1" type="number" class="calc-input" required>
                    <h4>%</h4>
                    @{
                       if (@ViewBag.Authentication)
                       {
                            <button type="button" class="indiv-percent def-button">Индивидуальная</button>
                       }
                    }
                </div>
                <div id="tdl" class="calc-to-block row">
                    <h4>Срок займа </h4>
                    <input id="ddly" size="2" value="0" type="number" class="calc-input" > <h4 class="ddly">(Года)</h4>
                    <input id="ddlm" size="2" value="1" type="number" class="calc-input" required> <h4 class="ddlm">Месяц</h4>
                </div>
                <div class="calc-to-block">
                    <h4>Дата выдачи</h4>
                    <input id="sdate" value="2021-01-01" type="date" class="calc-input" required>
                </div>
                <div class="calc-to-block">
                    <h4>Порядок погашения</h4>
                    <select id="tpay" class="calc-select">
                        <option value="a">Аннуитетный</option>
                        <option value="d">Дифференцированный</option>
                    </select>
                </div>
                <div class="calc-to-block">
                    <h4>Периодичность погашения</h4>
                    <select id="perpay" class="calc-select">
                        <option value="m">Eжемесячно</option>
                    </select>
                </div>
                @*<div id="fdate" class="calc-to-block">
                    <h4>Сроки досрочного погашения</h4>
                    <input value="2021-01-01" type="date" class="calc-input calc-input-hide" required>
                    <button type="button" data-new-deadline="yes" data-new-deadline-active="true" class="new-deadline-button">Да</button>
                    <button type="button" data-new-deadline="no" data-new-deadline-active="false" class="new-deadline-button currency-active">Нет</button>
                </div>*@
        </div>
        <button id='get-value-block' type="button" class="get-button get-value-block">
            Получить результат
        </button>
    </div>
</div>